version: '3'
services:
  airflow_docker:
    image: airflow_docker:latest

    environment:
      # Path of project's data folder (will be mounted to get produced data)
      - DATA_PATH=YOUR\PATH\TO\THE\PROJECT\MLOps_Pipeline_Orchetrator\kedrospaceship\data
      # Path of project's mlruns folder (will be mounted to access mlflow logged params and tags)
      - MLRUNS_PATH=YOUR\PATH\TO\THE\PROJECT\MLOps_Pipeline_Orchetrator\kedrospaceship\mlruns
      # Path of artifacts in docker container (same as local mlruns path; will be mounted to access mlflow logged artifacts)
      - ARTIFACTS_DOCKER_PATH=/YOUR/PATH/TO/THE/PROJECT/MLOps_Pipeline_Orchetrator/kedrospaceship/mlruns

    volumes:
      - .\airflow:/opt/airflow
      - //var/run/docker.sock:/var/run/docker.sock


    ports:
      - "8080:8080"

    command: airflow standalone
